// Generated by ts-to-zod
import { z } from 'zod';

const availabilityStatusSchema = z.any();

const openingHoursSchema = z.any();

const pricingUnitSchema = z.any();

const pricingSchema = z.any();

export const availabilityCalendarSchema = z.object({
  localDate: z.string(),
  available: z.boolean(),
  status: availabilityStatusSchema,
  vacancies: z.number().nullable(),
  capacity: z.number().nullable(),
  openingHours: z.array(openingHoursSchema),
  unitPricingFrom: z.array(pricingUnitSchema).optional(),
  pricingFrom: z.array(pricingSchema).optional(),
});
