/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { BookingAvailability } from './BookingAvailability';
import type { BookingCancellation } from './BookingCancellation';
import type { BookingStatus } from './BookingStatus';
import type { Contact } from './Contact';
import type { DeliveryMethod } from './DeliveryMethod';
import type { Option } from './Option';
import type { Pricing } from './Pricing';
import type { Product } from './Product';
import type { Ticket } from './Ticket';
import type { UnitItem } from './UnitItem';
export type Booking = {
  /**
   * A unique ID / UUID generated by the supplier system to identify the booking.
   */
  id: string;
  /**
   * A UUID you can set when generating the booking to use as an idempotency key.
   */
  uuid: string;
  /**
   * If `TRUE`, booking was created on test mode
   */
  testMode: boolean;
  /**
   * The reference set by the Reseller. A mandatory field for resellers to be set in the booking confirmation request.
   */
  resellerReference: string | null;
  /**
   * The reference set by the Reseller. A mandatory field for resellers to be set in the booking confirmation request.
   */
  supplierReference: string | null;
  /**
   * The status of the booking, possible values are:
   * `ON_HOLD` The booking is pending confirmation, this is the default value when you first create the booking.
   * `EXPIRED` If the booking is not confirmed before the expiration hold expires, it goes into an expired state.
   * `CONFIRMED` Once the confirmation call is made the booking is ready to be used.
   * `CANCELLED` If the booking is cancelled.
   * `PENDING` If the booking is pending outside availability confirmation.
   * `REDEEMED` If the booking is already redeemed.
   */
  status: BookingStatus;
  /**
   * An ISO8601 date time in UTC when the booking was created.
   */
  utcCreatedAt: string;
  /**
   * An ISO8601 date time in UTC when the booking was updated.
   */
  utcUpdatedAt: string | null;
  /**
   * An ISO8601 date times in UTC for when this booking is due to expire if the status is `ON_HOLD`.
   */
  utcExpiresAt: string | null;
  /**
   * An ISO8601 date time in UTC at when the booking was redeemed.
   */
  utcRedeemedAt: string | null;
  /**
   * An ISO8601 date time in UTC when the booking was confirmed.
   */
  utcConfirmedAt: string | null;
  /**
   * The product ID that identifies the product in the booking system to make this reservation.
   */
  productId: string;
  /**
   * A bookable product listed by a supplier.
   */
  product?: Product;
  /**
   * The product ID that identifies the product option in the booking system to make this reservation.
   */
  optionId: string;
  /**
   * The product ID that identifies the product option in the booking system to make this reservation.
   */
  option?: Option;
  /**
   * Product options are subdivisions of the original product that will affect price and / or duration. Within the OCTo spec, every product must contain an option.
   */
  cancellable: boolean;
  /**
   * A boolean field indicating whether this booking can be cancelled.
   */
  cancellation: BookingCancellation | null;
  /**
   * Whether the booking was made as freesale (without checking availability first).
   */
  freesale: boolean;
  /**
   * The availability id that was used in the request.
   */
  availabilityId: string;
  /**
   * The availability object that was booked.
   *
   */
  availability: BookingAvailability;
  /**
   * Contact details for the guests that will attend the tour/attraction. Contact schema can be applied to both the booking object (the main reservation) or the unit object (individual ticket holders - if the supplier requires this information)
   */
  contact: Contact;
  /**
   * Optional notes for the booking.
   */
  notes: string | null;
  /**
   * An array of delivery methods available for this booking.
   */
  deliveryMethods: Array<DeliveryMethod>;
  voucher: Ticket | null;
  /**
   * An array o`f unit items that will be included in the booking.
   */
  unitItems: Array<UnitItem>;
  /**
   * Is on the object when Pricing capability is requested.
   */
  pricing?: Pricing;
};
