// Generated by ts-to-zod
import { z } from 'zod';
import { pricingSchema } from './Pricing';
import { pricingUnitSchema } from './PricingUnit';

export const availabilityCalendarPricingSchema = z.object({
  unitPricingFrom: z.array(pricingUnitSchema).optional(),
  pricingFrom: z.array(pricingSchema).optional(),
});
