// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';

export const availabilitySchema = z.object({
  id: z.string(),
  localDateTimeStart: z.string(),
  localDateTimeEnd: z.string(),
  utcCutoffAt: z.string(),
  allDay: z.boolean(),
  available: z.boolean(),
  status: availabilityStatusSchema,
  vacancies: z.number().nullable(),
  capacity: z.number().nullable(),
  maxUnits: z.number().nullable(),
  openingHours: z.array(openingHoursSchema),
  unitPricing: z.array(pricingUnitSchema).optional(),
  pricing: pricingSchema.optional(),
  title: z.string().optional().nullable(),
  shortDescription: z.string().optional(),
});
