// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { pricingSchema } from './Pricing';
import { pricingUnitSchema } from './PricingUnit';

export const availabilityCalendarSchema = z.object({
  localDate: z.string(),
  available: z.boolean(),
  status: availabilityStatusSchema,
  vacancies: z.number().nullable(),
  capacity: z.number().nullable(),
  openingHours: z.array(openingHoursSchema),
  unitPricingFrom: z.array(pricingUnitSchema).optional(),
  pricingFrom: z.array(pricingSchema).optional(),
});
