// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityCheckBodyRule } from '../rules/AvailabilityCheckBody';
import { availabilityUnitSchema } from './AvailabilityUnit';

export const availabilityCheckBodySchema = z
  .object({
    productId: z.string(),
    optionId: z.string(),
    localDate: z.string().optional(),
    localDateStart: z.string().optional(),
    localDateEnd: z.string().optional(),
    availabilityIds: z.array(z.string()).optional(),
    units: z.array(availabilityUnitSchema).optional(),
    currency: z.string().optional(),
  })
  .superRefine(availabilityCheckBodyRule);
