// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityRule } from '../rules/Availability';
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { pricingSchema } from './Pricing';
import { pricingUnitSchema } from './PricingUnit';

export const availabilitySchema = z
  .object({
    id: z.string(),
    localDateTimeStart: z.string(),
    localDateTimeEnd: z.string(),
    utcCutoffAt: z.string(),
    allDay: z.boolean(),
    available: z.boolean(),
    status: availabilityStatusSchema,
    vacancies: z.number().nullable(),
    capacity: z.number().nullable(),
    maxUnits: z.number().nullable(),
    openingHours: z.array(openingHoursSchema),
    unitPricing: z.array(pricingUnitSchema).optional(),
    pricing: z.array(pricingSchema).optional(),
    title: z.string().optional().nullable(),
    shortDescription: z.string().optional(),
  })
  .superRefine(availabilityRule());
