// Generated by ts-to-zod
import { z } from 'zod';
import { bookingUnitItemSchema } from './BookingUnitItem';
import { bookingContactSchema } from './BookingContact';

export const bookingReservationSchemaSchema = z.object({
  uuid: z.string().optional(),
  productId: z.string(),
  optionId: z.string(),
  availabilityId: z.string().optional(),
  expirationMinutes: z.number().optional(),
  notes: z.string().optional().nullable(),
  unitItems: z.array(bookingUnitItemSchema),
  resellerReference: z.string().optional(),
  contact: bookingContactSchema.optional(),
  currency: z.string().optional().nullable(),
});
