// Generated by ts-to-zod
import { z } from 'zod';
import { bookingContactSchema } from './BookingContact';

export const bookingUnitItemSchema = z.object({
  uuid: z.string().optional(),
  unitId: z.string(),
  resellerReference: z.string().optional(),
  contact: bookingContactSchema.optional(),
});
