// Generated by ts-to-zod
import { z } from 'zod';
import { bookingUnitItemSchema } from './BookingUnitItem';

export const bookingReservationBodySchema = z.object({
  uuid: z.string().optional(),
  productId: z.string(),
  optionId: z.string(),
  availabilityId: z.string().optional(),
  expirationMinutes: z.number().optional(),
  notes: z.string().optional(),
  unitItems: z.array(bookingUnitItemSchema),
  currency: z.string().optional(),
});
