// Generated by ts-to-zod
import { z } from 'zod';
import { bookingRule } from '../rules/Booking';
import { availabilitySchema } from './Availability';
import { bookingCancellationSchema } from './BookingCancellation';
import { bookingStatusSchema } from './BookingStatus';
import { contactSchema } from './Contact';
import { deliveryMethodSchema } from './DeliveryMethod';
import { optionSchema } from './Option';
import { pricingSchema } from './Pricing';
import { productSchema } from './Product';
import { ticketSchema } from './Ticket';
import { unitItemSchema } from './UnitItem';

export const bookingSchema = z
  .object({
    id: z.string(),
    uuid: z.string(),
    testMode: z.boolean(),
    resellerReference: z.string().nullable(),
    supplierReference: z.string().nullable(),
    status: bookingStatusSchema,
    utcCreatedAt: z.string(),
    utcUpdatedAt: z.string(),
    utcExpiresAt: z.string().nullable(),
    utcRedeemedAt: z.string().nullable(),
    utcConfirmedAt: z.string().nullable(),
    productId: z.string(),
    product: productSchema.optional(),
    optionId: z.string(),
    option: optionSchema.optional(),
    cancellable: z.boolean(),
    cancellation: bookingCancellationSchema.nullable(),
    freesale: z.boolean(),
    availabilityId: z.string(),
    availability: availabilitySchema,
    contact: contactSchema,
    notes: z.string().nullable(),
    deliveryMethods: z.array(deliveryMethodSchema),
    voucher: ticketSchema.nullable(),
    unitItems: z.array(unitItemSchema),
    pricing: pricingSchema.optional(),
  })
  .superRefine(bookingRule());
