// Generated by ts-to-zod
import { z } from 'zod';
import { bookingContactSchema } from './BookingContact';
import { bookingUnitItemSchema } from './BookingUnitItem';

export const bookingUpdateBodySchema = z.object({
  resellerReference: z.string().optional(),
  productId: z.string().optional(),
  optionId: z.string().optional(),
  availabilityId: z.string().optional(),
  expirationMinutes: z.number().optional(),
  notes: z.string().optional(),
  emailReceipt: z.boolean().optional(),
  unitItems: z.array(bookingUnitItemSchema).optional(),
  contact: bookingContactSchema.optional(),
});
