// Generated by ts-to-zod
import { z } from 'zod';

export const bookingCancellationSchemaSchema = z.object({
  uuid: z.string(),
  reason: z.string().optional().nullable(),
  force: z.boolean().optional(),
});
