// Generated by ts-to-zod
import { z } from 'zod';
import { bookingContactSchema } from './BookingContact';
import { bookingUnitItemSchema } from './BookingUnitItem';

export const bookingConfirmationSchemaSchema = z.object({
  uuid: z.string(),
  emailReceipt: z.boolean().optional(),
  resellerReference: z.string().optional(),
  contact: bookingContactSchema,
  unitItems: z.array(bookingUnitItemSchema).optional(),
});
