// Generated by ts-to-zod
import { z } from 'zod';
import { capabilityIdSchema } from './CapabilityId';

export const capabilitySchema = z.object({
  id: capabilityIdSchema,
  revision: z.number(),
  required: z.boolean(),
  dependencies: z.array(capabilityIdSchema),
  docs: z.string().nullable(),
});
