// Generated by ts-to-zod
import { z } from 'zod';
import { commentaryFormatSchema } from './CommentaryFormat';

export const commentarySchema = z.object({
  format: commentaryFormatSchema,
  language: z.string(),
});
