// Generated by ts-to-zod
import { z } from 'zod';

export const contactSchema = z.object({
  fullName: z.string().nullable(),
  firstName: z.string().nullable(),
  lastName: z.string().nullable(),
  emailAddress: z.string().nullable(),
  phoneNumber: z.string().nullable(),
  locales: z.array(z.string()),
  postalCode: z.string().nullable(),
  country: z.string().nullable(),
  notes: z.string().nullable(),
});
