// Generated by ts-to-zod
import { z } from 'zod';
import { baseErrorSchema } from './BaseError';

export const errorInvalidProductIDSchema = baseErrorSchema.and(
  z.object({
    productId: z.string(),
  }),
);
