// Generated by ts-to-zod
import { z } from 'zod';
import { baseErrorSchema } from './BaseError';

export const errorInvalidUnitIDSchema = baseErrorSchema.and(
  z.object({
    unitId: z.string(),
  }),
);
