// Generated by ts-to-zod
import { z } from 'zod';
import { baseErrorSchema } from './BaseError';

export const errorInvalidAvailabilityIDSchema = baseErrorSchema.and(
  z.object({
    availabilityId: z.string(),
  }),
);
