// Generated by ts-to-zod
import { z } from 'zod';
import { baseErrorSchema } from './BaseError';

export const errorInvalidBookingUUIDSchema = baseErrorSchema.and(
  z.object({
    uuid: z.string(),
  }),
);
