// Generated by ts-to-zod
import { z } from 'zod';
import { featureTypeSchema } from './FeatureType';

export const featureSchema = z.object({
  shortDescription: z.string().nullable(),
  type: featureTypeSchema,
});
