// Generated by ts-to-zod
import { z } from 'zod';

export const identifiersSchema = z.object({
  googlePlaceId: z.string().nullable(),
  applePlaceId: z.string().nullable(),
  tripadvisorLocationId: z.string().nullable(),
  yelpPlaceId: z.string().nullable(),
  facebookPlaceId: z.string().nullable(),
  foursquarePlaceId: z.string().nullable(),
  baiduPlaceId: z.string().nullable(),
  amapPlaceId: z.string().nullable(),
});
