// Generated by ts-to-zod
import { z } from 'zod';
import { locationTypeSchema } from './LocationType';
import { placeSchema } from './Place';

export const locationSchema = z.object({
  title: z.string().nullable(),
  shortDescription: z.string().nullable(),
  types: z.array(locationTypeSchema),
  minutesTo: z.number().nullable(),
  minutesAt: z.number().nullable(),
  place: placeSchema,
});
