// Generated by ts-to-zod
import { z } from 'zod';
import { cancellationCutoffUnitSchema } from './CancellationCutoffUnit';
import { categoryLabelSchema } from './CategoryLabel';
import { commentarySchema } from './Commentary';
import { contactFieldSchema } from './ContactField';
import { fAQSchema } from './FAQ';
import { featureSchema } from './Feature';
import { locationSchema } from './Location';
import { mediaSchema } from './Media';
import { optionRestrictionsSchema } from './OptionRestrictions';
import { pricingSchema } from './Pricing';
import { unitSchema } from './Unit';

export const optionSchema = z.object({
  id: z.string(),
  default: z.boolean(),
  internalName: z.string(),
  reference: z.string().nullable(),
  availabilityLocalStartTimes: z.array(z.string()),
  cancellationCutoff: z.string(),
  cancellationCutoffAmount: z.number(),
  cancellationCutoffUnit: cancellationCutoffUnitSchema,
  requiredContactFields: z.array(contactFieldSchema),
  restrictions: optionRestrictionsSchema,
  units: z.array(unitSchema),
  pricingFrom: z.array(pricingSchema).optional(),
  pricing: z.array(pricingSchema).optional(),
  title: z.string().optional(),
  shortDescription: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  features: z.array(featureSchema).optional(),
  faqs: z.array(fAQSchema).optional(),
  media: z.array(mediaSchema).optional(),
  locations: z.array(locationSchema).optional(),
  categoryLabels: z.array(categoryLabelSchema).optional(),
  durationMinutesFrom: z.number().optional(),
  durationMinutesTo: z.number().optional().nullable(),
  commentary: z.array(commentarySchema).optional(),
});
