// Generated by ts-to-zod
import { z } from 'zod';
import { identifiersSchema } from './Identifiers';
import { postalAddressSchema } from './PostalAddress';

export const placeSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  postalAddress: postalAddressSchema,
  identifiers: identifiersSchema,
  sameAs: z.array(z.string()),
});
