// Generated by ts-to-zod
import { z } from 'zod';

export const postalAddressSchema = z.object({
  streetAddress: z.string().nullable(),
  addressLocality: z.string().nullable(),
  addressRegion: z.string().nullable(),
  postalCode: z.string().nullable(),
  addressCountry: z.string().nullable(),
  postOfficeBoxNumber: z.string().nullable(),
});
