// Generated by ts-to-zod
import { z } from 'zod';
import { categoryLabelSchema } from './CategoryLabel';
import { commentarySchema } from './Commentary';
import { fAQSchema } from './FAQ';
import { featureSchema } from './Feature';
import { locationSchema } from './Location';
import { mediaSchema } from './Media';

export const productContentSchema = z.object({
  title: z.string().optional(),
  shortDescription: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  features: z.array(featureSchema).optional(),
  faqs: z.array(fAQSchema).optional(),
  media: z.array(mediaSchema).optional(),
  locations: z.array(locationSchema).optional(),
  categoryLabels: z.array(categoryLabelSchema).optional(),
  durationMinutesFrom: z.number().optional(),
  durationMinutesTo: z.number().optional().nullable(),
  commentary: z.array(commentarySchema).optional(),
});
