// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityTypeSchema } from './AvailabilityType';
import { categoryLabelSchema } from './CategoryLabel';
import { commentarySchema } from './Commentary';
import { deliveryFormatSchema } from './DeliveryFormat';
import { deliveryMethodSchema } from './DeliveryMethod';
import { fAQSchema } from './FAQ';
import { featureSchema } from './Feature';
import { locationSchema } from './Location';
import { mediaSchema } from './Media';
import { optionSchema } from './Option';
import { pricingPerSchema } from './PricingPer';
import { redemptionMethodSchema } from './RedemptionMethod';

export const productSchema = z.object({
  id: z.string(),
  internalName: z.string(),
  reference: z.string().nullable(),
  locale: z.string(),
  timeZone: z.string().optional(),
  allowFreesale: z.boolean(),
  instantConfirmation: z.boolean(),
  instantDelivery: z.boolean(),
  availabilityRequired: z.boolean(),
  availabilityType: availabilityTypeSchema,
  deliveryFormats: z.array(deliveryFormatSchema),
  deliveryMethods: z.array(deliveryMethodSchema),
  redemptionMethod: redemptionMethodSchema,
  options: z.array(optionSchema),
  defaultCurrency: z.string().optional(),
  availableCurrencies: z.array(z.string()).optional(),
  pricingPer: pricingPerSchema.optional(),
  title: z.string().optional(),
  shortDescription: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  features: z.array(featureSchema).optional(),
  faqs: z.array(fAQSchema).optional(),
  media: z.array(mediaSchema).optional(),
  locations: z.array(locationSchema).optional(),
  categoryLabels: z.array(categoryLabelSchema).optional(),
  durationMinutesFrom: z.number().optional(),
  durationMinutesTo: z.number().optional().nullable(),
  commentary: z.array(commentarySchema).optional(),
});
