// Generated by ts-to-zod
import { z } from 'zod';

export const restrictionsContentSchema = z.object({
  minHeight: z.number().optional(),
  maxHeight: z.number().optional(),
  heightUnit: z.string().optional(),
  minWeight: z.number().optional(),
  maxWeight: z.number().optional(),
  weightUnit: z.string().optional(),
});
