// Generated by ts-to-zod
import { z } from 'zod';
import { mediaSchema } from './Media';
import { supplierContactSchema } from './SupplierContact';

export const supplierSchema = z.object({
  id: z.string(),
  name: z.string(),
  endpoint: z.string(),
  contact: supplierContactSchema,
  shortDescription: z.string().optional().nullable(),
  media: z.array(mediaSchema).optional(),
});
