// Generated by ts-to-zod
import { z } from 'zod';
import { mediaSchema } from './Media';

export const supplierContentSchema = z.object({
  shortDescription: z.string().optional().nullable(),
  media: z.array(mediaSchema).optional(),
});
