// Generated by ts-to-zod
import { z } from 'zod';
import { featureSchema } from './Feature';

export const unitContentSchema = z.object({
  title: z.string().optional().nullable(),
  shortDescription: z.string().optional(),
  features: z.array(featureSchema).optional(),
});
