// Generated by ts-to-zod
import { z } from 'zod';
import { unitTypeSchema } from './UnitType';
import { unitRestrictionsSchema } from './UnitRestrictions';
import { contactFieldSchema } from './ContactField';
import { pricingSchema } from './Pricing';
import { featureSchema } from './Feature';

export const unitSchema = z.object({
  id: z.string(),
  internalName: z.string(),
  reference: z.string().nullable(),
  type: unitTypeSchema,
  restrictions: unitRestrictionsSchema,
  requiredContactFields: z.array(contactFieldSchema),
  pricingFrom: z.array(pricingSchema).optional(),
  pricing: z.array(pricingSchema).optional(),
  title: z.string().optional().nullable(),
  shortDescription: z.string().optional(),
  features: z.array(featureSchema).optional(),
});
