// Generated by ts-to-zod
import { z } from 'zod';
import { bookingStatusSchema } from './BookingStatus';
import { contactSchema } from './Contact';
import { pricingSchema } from './Pricing';
import { ticketSchema } from './Ticket';
import { unitSchema } from './Unit';

export const unitItemSchema = z.object({
  uuid: z.string(),
  resellerReference: z.string().nullable(),
  supplierReference: z.string().nullable(),
  unitId: z.string(),
  unit: unitSchema.optional(),
  status: bookingStatusSchema,
  utcRedeemedAt: z.string().nullable(),
  contact: contactSchema,
  ticket: ticketSchema.nullable(),
  pricing: pricingSchema.optional(),
});
