// Generated by ts-to-zod
import { z } from 'zod';
import { openingHoursSchema } from './OpeningHours';

export const bookingAvailabilitySchema = z.object({
  id: z.string(),
  localDateTimeStart: z.string(),
  localDateTimeEnd: z.string(),
  allDay: z.boolean(),
  openingHours: z.array(openingHoursSchema),
});
