// Generated by ts-to-zod
import { z } from 'zod';

export const categorySchema = z.object({
  id: z.string(),
  default: z.boolean(),
  name: z.string().nullable(),
  title: z.string().nullable(),
  shortDescription: z.string().nullable(),
  bannerImageUrl: z.string().nullable(),
  coverImageUrl: z.string().nullable(),
  productIds: z.array(z.string()),
});
