// Generated by ts-to-zod
import { z } from 'zod';
import { categorySchema } from './Category';
import { supplierContactSchema } from './SupplierContact';

export const destinationSchema = z.object({
  id: z.string(),
  default: z.boolean(),
  name: z.string().nullable(),
  country: z.string().nullable(),
  contact: supplierContactSchema,
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  googlePlaceId: z.string().nullable(),
  bannerImageUrl: z.string().nullable(),
  coverImageUrl: z.string().nullable(),
  videoUrl: z.string().nullable(),
  facebookUrl: z.string().nullable(),
  googleUrl: z.string().nullable(),
  tripadvisorUrl: z.string().nullable(),
  twitterUrl: z.string().nullable(),
  youtubeUrl: z.string().nullable(),
  instagramUrl: z.string().nullable(),
  categories: z.array(categorySchema),
});
