// Generated by ts-to-zod
import { z } from 'zod';
import { baseErrorSchema } from './BaseError';

export const errorInvalidOptionIDSchema = baseErrorSchema.and(
  z.object({
    optionId: z.string(),
  }),
);
