// Generated by ts-to-zod
import { z } from 'zod';
import { cancellationCutoffUnitSchema } from './CancellationCutoffUnit';
import { contactFieldSchema } from './ContactField';
import { optionRestrictionsSchema } from './OptionRestrictions';
import { pricingSchema } from './Pricing';
import { unitSchema } from './Unit';

export const optionSchema = z.object({
  id: z.string(),
  default: z.boolean(),
  internalName: z.string(),
  reference: z.string().nullable(),
  availabilityLocalStartTimes: z.array(z.string()),
  cancellationCutoff: z.string(),
  cancellationCutoffAmount: z.number(),
  cancellationCutoffUnit: cancellationCutoffUnitSchema,
  requiredContactFields: z.array(contactFieldSchema),
  restrictions: optionRestrictionsSchema,
  units: z.array(unitSchema),
  pricingFrom: z.array(pricingSchema).optional(),
  pricing: z.array(pricingSchema).optional(),
});
