// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityTypeSchema } from './AvailabilityType';
import { deliveryFormatSchema } from './DeliveryFormat';
import { deliveryMethodSchema } from './DeliveryMethod';
import { optionSchema } from './Option';
import { pricingPerSchema } from './PricingPer';
import { redemptionMethodSchema } from './RedemptionMethod';

export const productSchema = z.object({
  id: z.string(),
  internalName: z.string(),
  reference: z.string().nullable(),
  locale: z.string(),
  timeZone: z.string().optional(),
  allowFreesale: z.boolean(),
  instantConfirmation: z.boolean(),
  instantDelivery: z.boolean(),
  availabilityRequired: z.boolean(),
  availabilityType: availabilityTypeSchema,
  deliveryFormats: z.array(deliveryFormatSchema),
  deliveryMethods: z.array(deliveryMethodSchema),
  redemptionMethod: redemptionMethodSchema,
  options: z.array(optionSchema),
  defaultCurrency: z.string().optional(),
  availableCurrencies: z.array(z.string()).optional(),
  pricingPer: pricingPerSchema.optional(),
});
