// Generated by ts-to-zod
import { z } from 'zod';

export const restrictionsSchema = z.object({
  minAge: z.number(),
  maxAge: z.number(),
  idRequired: z.boolean(),
  minQuantity: z.number().nullable(),
  maxQuantity: z.number().nullable(),
  paxCount: z.number(),
  accompaniedBy: z.array(z.string()),
});
