// Generated by ts-to-zod
import { z } from 'zod';
import { capabilitySchema } from './Capability';
import { destinationSchema } from './Destination';
import { supplierContactSchema } from './SupplierContact';

export const supplierSchema = z.object({
  id: z.string(),
  name: z.string(),
  endpoint: z.string(),
  contact: supplierContactSchema,
  capabilities: z.array(capabilitySchema),
  country: z.string().optional().nullable(),
  destinations: z.array(destinationSchema).optional(),
});
