// Generated by ts-to-zod
import { z } from 'zod';
import { contactFieldSchema } from './ContactField';
import { pricingSchema } from './Pricing';
import { restrictionsSchema } from './Restrictions';
import { unitTypeSchema } from './UnitType';

export const unitSchema = z.object({
  id: z.string(),
  internalName: z.string(),
  reference: z.string().nullable(),
  type: unitTypeSchema,
  restrictions: restrictionsSchema,
  requiredContactFields: z.array(contactFieldSchema),
  pricingFrom: z.array(pricingSchema).optional(),
  pricing: z.array(pricingSchema).optional(),
});
