/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Availability } from './Availability';
import type { BookingCancellation } from './BookingCancellation';
import type { BookingStatus } from './BookingStatus';
import type { Contact } from './Contact';
import type { DeliveryMethod } from './DeliveryMethod';
import type { Option } from './Option';
import type { Pricing } from './Pricing';
import type { Product } from './Product';
import type { Ticket } from './Ticket';
import type { UnitItem } from './UnitItem';
export type Booking = {
  /**
   * A unique identifier generated by the supplier system for the booking. This ID ensures traceability and must be unique within the system.
   */
  id: string;
  /**
   * An optional idempotency key set when creating a booking to prevent duplicate bookings in case of retries. Used for API calls.
   */
  uuid: string;
  /**
   * Indicates whether the booking was created in test mode. If true, it is a test booking.
   */
  testMode: boolean;
  /**
   * A reference provided by the reseller to identify the booking.
   */
  resellerReference: string | null;
  /**
   * A reference provided by the reseller to identify the booking.
   */
  supplierReference: string | null;
  /**
   * Represents the current state of the booking:
   * ON_HOLD: Awaiting confirmation.
   * EXPIRED: Not confirmed within the hold expiration time.
   * CONFIRMED: Successfully confirmed.
   * CANCELLED: The booking was canceled.
   * PENDING: Awaiting external confirmation.
   * REDEEMED: The booking has been used.
   */
  status: BookingStatus;
  /**
   * An ISO8601 date time in UTC when the booking was created.
   */
  utcCreatedAt: string;
  /**
   * An ISO8601 date time in UTC when the booking was last updated, if applicable.
   */
  utcUpdatedAt: string;
  /**
   * An ISO8601 date times in UTC for when this booking is due to expire if the status is ON_HOLD.
   */
  utcExpiresAt: string | null;
  /**
   * An ISO8601 date time in UTC at when the booking was redeemed, if applicable.
   */
  utcRedeemedAt: string | null;
  /**
   * An ISO8601 date time in UTC when the booking was confirmed, if applicable.
   */
  utcConfirmedAt: string | null;
  /**
   * The ID of product booked.
   */
  productId: string;
  /**
   * The object of booked product.
   */
  product?: Product;
  /**
   * The ID of option booked.
   */
  optionId: string;
  /**
   * The ID of option booked.
   */
  option?: Option;
  /**
   * The object of booked option.
   */
  cancellable: boolean;
  /**
   * A boolean field indicating whether this booking can be cancelled.
   */
  cancellation: BookingCancellation | null;
  /**
   * Indicates if the booking was made without checking availability.
   */
  freesale: boolean;
  /**
   * The ID of availability booked.
   */
  availabilityId: string;
  /**
   * The availability object that was booked.
   */
  availability: Availability;
  /**
   * Customer contact details for the booking (see unit object for per ticket / unit details).
   */
  contact: Contact;
  /**
   * Customer-facing public notes for the booking.
   */
  notes: string | null;
  /**
   * Specifies all supported methods of how tickets or vouchers for this booking are delivered.
   * TICKET: Delivered individually per unit in the booking, where each person or unit receives a separate ticket. These will be provided in the ticket object.
   * VOUCHER: Delivered as a single voucher for the entire booking, consolidating all units under one document. These will be provided in the voucher object.
   * This field ensures clarity on the format of ticket or voucher delivery to resellers and customers.
   */
  deliveryMethods: Array<DeliveryMethod>;
  /**
   * Details for voucher-based delivery, provided when VOUCHER is one of deliveryMethods.
   */
  voucher: Ticket | null;
  /**
   * An array of unit items included in the booking.
   */
  unitItems: Array<UnitItem>;
  /**
   * Is on the object when Pricing capability is requested.
   */
  pricing?: Pricing;
};
