/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum CategoryLabel {
  MULTI_DAY = 'multi-day',
  CITY_CARDS = 'city-cards',
  ADULTS_ONLY = 'adults-only',
  ANIMALS = 'animals',
  AUDIO_GUIDE = 'audio-guide',
  BEACHES = 'beaches',
  BIKE_TOURS = 'bike-tours',
  BOAT_TOURS = 'boat-tours',
  CLASSES = 'classes',
  DAY_TRIPS = 'day-trips',
  FAMILY_FRIENDLY = 'family-friendly',
  FAST_TRACK = 'fast-track',
  FOOD = 'food',
  GUIDED_TOURS = 'guided-tours',
  HISTORY = 'history',
  HOP_ON_HOP_OFF = 'hop-on-hop-off',
  LITERATURE = 'literature',
  LIVE_MUSIC = 'live-music',
  MUSEUMS = 'museums',
  NIGHTLIFE = 'nightlife',
  OUTDOORS = 'outdoors',
  PRIVATE_TOURS = 'private-tours',
  ROMANTIC = 'romantic',
  RECURRING_EVENTS = 'recurring-events',
  SELF_GUIDED = 'self-guided',
  SMALL_GROUP_TOURS = 'small-group-tours',
  SPORTS = 'sports',
  THEME_PARKS = 'theme-parks',
  WALKING_TOURS = 'walking-tours',
  WHEELCHAIR_ACCESSIBLE = 'wheelchair-accessible',
  ACCOMMODATION_INCLUDED = 'accommodation-included',
  TRIP_DIFFICULTY_EASY = 'trip-difficulty-easy',
  TRIP_DIFFICULTY_MEDIUM = 'trip-difficulty-medium',
  TRIP_DIFFICULTY_HARD = 'trip-difficulty-hard',
}
