/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum FeatureType {
  INCLUSION = 'INCLUSION',
  EXCLUSION = 'EXCLUSION',
  HIGHLIGHT = 'HIGHLIGHT',
  PREBOOKING_INFORMATION = 'PREBOOKING_INFORMATION',
  PREARRIVAL_INFORMATION = 'PREARRIVAL_INFORMATION',
  REDEMPTION_INSTRUCTION = 'REDEMPTION_INSTRUCTION',
  ACCESSIBILITY_INFORMATION = 'ACCESSIBILITY_INFORMATION',
  ADDITIONAL_INFORMATION = 'ADDITIONAL_INFORMATION',
  BOOKING_TERM = 'BOOKING_TERM',
  CANCELLATION_TERM = 'CANCELLATION_TERM',
}
