/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type { Availability } from './models/Availability';
export type { AvailabilityCalendar } from './models/AvailabilityCalendar';
export type { AvailabilityCalendarBody } from './models/AvailabilityCalendarBody';
export type { AvailabilityCalendarPricing } from './models/AvailabilityCalendarPricing';
export type { AvailabilityCalendarPricingBody } from './models/AvailabilityCalendarPricingBody';
export type { AvailabilityCalendarRequest } from './models/AvailabilityCalendarRequest';
export type { AvailabilityCheckBody } from './models/AvailabilityCheckBody';
export type { AvailabilityCheckRequest } from './models/AvailabilityCheckRequest';
export type { AvailabilityContent } from './models/AvailabilityContent';
export type { AvailabilityPricing } from './models/AvailabilityPricing';
export type { AvailabilityPricingBody } from './models/AvailabilityPricingBody';
export { AvailabilityStatus } from './models/AvailabilityStatus';
export { AvailabilityType } from './models/AvailabilityType';
export type { AvailabilityUnit } from './models/AvailabilityUnit';
export type { BaseError } from './models/BaseError';
export type { Booking } from './models/Booking';
export type { BookingCancellation } from './models/BookingCancellation';
export type { BookingCancellationBody } from './models/BookingCancellationBody';
export type { BookingCancellationRequest_uuid } from './models/BookingCancellationRequest_uuid';
export type { BookingConfirmationBody } from './models/BookingConfirmationBody';
export type { BookingConfirmationRequest_uuid } from './models/BookingConfirmationRequest_uuid';
export type { BookingContact } from './models/BookingContact';
export type { BookingPricing } from './models/BookingPricing';
export type { BookingReservationBody } from './models/BookingReservationBody';
export type { BookingReservationPricingBody } from './models/BookingReservationPricingBody';
export type { BookingReservationRequest } from './models/BookingReservationRequest';
export { BookingStatus } from './models/BookingStatus';
export type { BookingUnitItem } from './models/BookingUnitItem';
export type { BookingUpdateBody } from './models/BookingUpdateBody';
export type { BookingUpdateRequest_uuid } from './models/BookingUpdateRequest_uuid';
export { CancellationCutoffUnit } from './models/CancellationCutoffUnit';
export { Capability, CapabilityId } from './models/Capability';
export { CategoryLabel } from './models/CategoryLabel';
export type { Commentary } from './models/Commentary';
export { CommentaryFormat } from './models/CommentaryFormat';
export type { Contact } from './models/Contact';
export { ContactField } from './models/ContactField';
export { DeliveryFormat } from './models/DeliveryFormat';
export { DeliveryMethod } from './models/DeliveryMethod';
export type { DeliveryOption } from './models/DeliveryOption';
export type { ErrorBadRequest } from './models/ErrorBadRequest';
export type { ErrorForbidden } from './models/ErrorForbidden';
export type { ErrorInternalServerError } from './models/ErrorInternalServerError';
export type { ErrorInvalidAvailabilityID } from './models/ErrorInvalidAvailabilityID';
export type { ErrorInvalidBookingUUID } from './models/ErrorInvalidBookingUUID';
export type { ErrorInvalidOptionID } from './models/ErrorInvalidOptionID';
export type { ErrorInvalidProductID } from './models/ErrorInvalidProductID';
export type { ErrorInvalidUnitID } from './models/ErrorInvalidUnitID';
export type { ErrorUnauthorized } from './models/ErrorUnauthorized';
export type { ErrorUnprocessableEntity } from './models/ErrorUnprocessableEntity';
export type { ExtendReservationBody } from './models/ExtendReservationBody';
export type { ExtendReservationRequest_uuid } from './models/ExtendReservationRequest_uuid';
export type { FAQ } from './models/FAQ';
export type { Feature } from './models/Feature';
export { FeatureType } from './models/FeatureType';
export type { GetBookingRequest_uuid } from './models/GetBookingRequest_uuid';
export type { GetBookingsRequest_localDate } from './models/GetBookingsRequest_localDate';
export type { GetBookingsRequest_localDateEnd } from './models/GetBookingsRequest_localDateEnd';
export type { GetBookingsRequest_localDateStart } from './models/GetBookingsRequest_localDateStart';
export type { GetBookingsRequest_optionId } from './models/GetBookingsRequest_optionId';
export type { GetBookingsRequest_productId } from './models/GetBookingsRequest_productId';
export type { GetBookingsRequest_resellerReference } from './models/GetBookingsRequest_resellerReference';
export type { GetBookingsRequest_supplierReference } from './models/GetBookingsRequest_supplierReference';
export type { GetProductRequest_id } from './models/GetProductRequest_id';
export type { GetProductsRequest } from './models/GetProductsRequest';
export type { GetSupplierRequest } from './models/GetSupplierRequest';
export { Gift } from './models/Gift';
export type { Identifiers } from './models/Identifiers';
export type { Location } from './models/Location';
export { LocationType } from './models/LocationType';
export { Mapping } from './models/Mapping';
export type { Media } from './models/Media';
export { MediaRel } from './models/MediaRel';
export { MediaType } from './models/MediaType';
export { Offer } from './models/Offer';
export type { OpeningHours } from './models/OpeningHours';
export type { Option } from './models/Option';
export type { OptionContent } from './models/OptionContent';
export type { OptionPricing } from './models/OptionPricing';
export type { OptionRestrictions } from './models/OptionRestrictions';
export { Order } from './models/Order';
export type { Place } from './models/Place';
export type { PostalAddress } from './models/PostalAddress';
export type { Pricing } from './models/Pricing';
export { PricingPer } from './models/PricingPer';
export type { PricingUnit } from './models/PricingUnit';
export type { Product } from './models/Product';
export type { ProductContent } from './models/ProductContent';
export type { ProductPricing } from './models/ProductPricing';
export { RedemptionMethod } from './models/RedemptionMethod';
export { Refund } from './models/Refund';
export type { RequestHeaders_octoCapabilities } from './models/RequestHeaders_octoCapabilities';
export type { RequestHeadersContent } from './models/RequestHeadersContent';
export type { ResponseHeaders } from './models/ResponseHeaders';
export type { ResponseHeadersContent } from './models/ResponseHeadersContent';
export type { RestrictionsContent } from './models/RestrictionsContent';
export type { Supplier } from './models/Supplier';
export type { SupplierContact } from './models/SupplierContact';
export type { SupplierContent } from './models/SupplierContent';
export type { Tax } from './models/Tax';
export type { Ticket } from './models/Ticket';
export type { Unit } from './models/Unit';
export type { UnitContent } from './models/UnitContent';
export type { UnitItem } from './models/UnitItem';
export type { UnitItemPricing } from './models/UnitItemPricing';
export type { UnitPricing } from './models/UnitPricing';
export type { UnitRestrictions } from './models/UnitRestrictions';
export { UnitType } from './models/UnitType';
export { Webhook } from './models/Webhook';
export { availabilitySchema } from './schemas/Availability';
export { availabilityCalendarSchema } from './schemas/AvailabilityCalendar';
export { availabilityCalendarBodySchema } from './schemas/AvailabilityCalendarBody';
export { availabilityCalendarPricingSchema } from './schemas/AvailabilityCalendarPricing';
export { availabilityCalendarPricingBodySchema } from './schemas/AvailabilityCalendarPricingBody';
export { availabilityCalendarRequestSchema } from './schemas/AvailabilityCalendarRequest';
export { availabilityCheckBodySchema } from './schemas/AvailabilityCheckBody';
export { availabilityCheckRequestSchema } from './schemas/AvailabilityCheckRequest';
export { availabilityContentSchema } from './schemas/AvailabilityContent';
export { availabilityPricingSchema } from './schemas/AvailabilityPricing';
export { availabilityPricingBodySchema } from './schemas/AvailabilityPricingBody';
export { availabilityStatusSchema } from './schemas/AvailabilityStatus';
export { availabilityTypeSchema } from './schemas/AvailabilityType';
export { availabilityUnitSchema } from './schemas/AvailabilityUnit';
export { baseErrorSchema } from './schemas/BaseError';
export { bookingSchema } from './schemas/Booking';
export { bookingCancellationSchema } from './schemas/BookingCancellation';
export { bookingCancellationBodySchema } from './schemas/BookingCancellationBody';
export { bookingCancellationRequest_uuidSchema } from './schemas/BookingCancellationRequest_uuid';
export { bookingConfirmationBodySchema } from './schemas/BookingConfirmationBody';
export { bookingConfirmationRequest_uuidSchema } from './schemas/BookingConfirmationRequest_uuid';
export { bookingContactSchema } from './schemas/BookingContact';
export { bookingPricingSchema } from './schemas/BookingPricing';
export { bookingReservationBodySchema } from './schemas/BookingReservationBody';
export { bookingReservationPricingBodySchema } from './schemas/BookingReservationPricingBody';
export { bookingReservationRequestSchema } from './schemas/BookingReservationRequest';
export { bookingStatusSchema } from './schemas/BookingStatus';
export { bookingUnitItemSchema } from './schemas/BookingUnitItem';
export { bookingUpdateBodySchema } from './schemas/BookingUpdateBody';
export { bookingUpdateRequest_uuidSchema } from './schemas/BookingUpdateRequest_uuid';
export { cancellationCutoffUnitSchema } from './schemas/CancellationCutoffUnit';
export { categoryLabelSchema } from './schemas/CategoryLabel';
export { commentarySchema } from './schemas/Commentary';
export { commentaryFormatSchema } from './schemas/CommentaryFormat';
export { contactSchema } from './schemas/Contact';
export { contactFieldSchema } from './schemas/ContactField';
export { deliveryFormatSchema } from './schemas/DeliveryFormat';
export { deliveryMethodSchema } from './schemas/DeliveryMethod';
export { deliveryOptionSchema } from './schemas/DeliveryOption';
export { errorBadRequestSchema } from './schemas/ErrorBadRequest';
export { errorForbiddenSchema } from './schemas/ErrorForbidden';
export { errorInternalServerErrorSchema } from './schemas/ErrorInternalServerError';
export { errorInvalidAvailabilityIDSchema } from './schemas/ErrorInvalidAvailabilityID';
export { errorInvalidBookingUUIDSchema } from './schemas/ErrorInvalidBookingUUID';
export { errorInvalidOptionIDSchema } from './schemas/ErrorInvalidOptionID';
export { errorInvalidProductIDSchema } from './schemas/ErrorInvalidProductID';
export { errorInvalidUnitIDSchema } from './schemas/ErrorInvalidUnitID';
export { errorUnauthorizedSchema } from './schemas/ErrorUnauthorized';
export { errorUnprocessableEntitySchema } from './schemas/ErrorUnprocessableEntity';
export { extendReservationBodySchema } from './schemas/ExtendReservationBody';
export { extendReservationRequest_uuidSchema } from './schemas/ExtendReservationRequest_uuid';
export { fAQSchema } from './schemas/FAQ';
export { featureSchema } from './schemas/Feature';
export { featureTypeSchema } from './schemas/FeatureType';
export { getBookingRequest_uuidSchema } from './schemas/GetBookingRequest_uuid';
export { getBookingsRequest_localDateSchema } from './schemas/GetBookingsRequest_localDate';
export { getBookingsRequest_localDateEndSchema } from './schemas/GetBookingsRequest_localDateEnd';
export { getBookingsRequest_localDateStartSchema } from './schemas/GetBookingsRequest_localDateStart';
export { getBookingsRequest_optionIdSchema } from './schemas/GetBookingsRequest_optionId';
export { getBookingsRequest_productIdSchema } from './schemas/GetBookingsRequest_productId';
export { getBookingsRequest_resellerReferenceSchema } from './schemas/GetBookingsRequest_resellerReference';
export { getBookingsRequest_supplierReferenceSchema } from './schemas/GetBookingsRequest_supplierReference';
export { getProductRequest_idSchema } from './schemas/GetProductRequest_id';
export { getProductsRequestSchema } from './schemas/GetProductsRequest';
export { getSupplierRequestSchema } from './schemas/GetSupplierRequest';
export { identifiersSchema } from './schemas/Identifiers';
export { locationSchema } from './schemas/Location';
export { locationTypeSchema } from './schemas/LocationType';
export { mediaSchema } from './schemas/Media';
export { mediaRelSchema } from './schemas/MediaRel';
export { mediaTypeSchema } from './schemas/MediaType';
export { openingHoursSchema } from './schemas/OpeningHours';
export { optionSchema } from './schemas/Option';
export { optionContentSchema } from './schemas/OptionContent';
export { optionPricingSchema } from './schemas/OptionPricing';
export { optionRestrictionsSchema } from './schemas/OptionRestrictions';
export { placeSchema } from './schemas/Place';
export { postalAddressSchema } from './schemas/PostalAddress';
export { pricingSchema } from './schemas/Pricing';
export { pricingPerSchema } from './schemas/PricingPer';
export { pricingUnitSchema } from './schemas/PricingUnit';
export { productSchema } from './schemas/Product';
export { productContentSchema } from './schemas/ProductContent';
export { productPricingSchema } from './schemas/ProductPricing';
export { redemptionMethodSchema } from './schemas/RedemptionMethod';
export { refundSchema } from './schemas/Refund';
export { requestHeaders_octoCapabilitiesSchema } from './schemas/RequestHeaders_octoCapabilities';
export { requestHeadersContentSchema } from './schemas/RequestHeadersContent';
export { responseHeadersSchema } from './schemas/ResponseHeaders';
export { responseHeadersContentSchema } from './schemas/ResponseHeadersContent';
export { restrictionsContentSchema } from './schemas/RestrictionsContent';
export { supplierSchema } from './schemas/Supplier';
export { supplierContactSchema } from './schemas/SupplierContact';
export { supplierContentSchema } from './schemas/SupplierContent';
export { taxSchema } from './schemas/Tax';
export { ticketSchema } from './schemas/Ticket';
export { unitSchema } from './schemas/Unit';
export { unitContentSchema } from './schemas/UnitContent';
export { unitItemSchema } from './schemas/UnitItem';
export { unitItemPricingSchema } from './schemas/UnitItemPricing';
export { unitPricingSchema } from './schemas/UnitPricing';
export { unitRestrictionsSchema } from './schemas/UnitRestrictions';
export { unitTypeSchema } from './schemas/UnitType';
